name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  test_release:
    uses: ./.github/workflows/tests.yml

  create_release:
    needs: [ test_release ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/ansible_collections/adhawkins/borgbase

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}

    - name: Install Ansible
      run: pip install ansible

    - uses: actions/download-artifact@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(grep "^version:" ${{github.workspace}}/ansible_collections/adhawkins/borgbase/galaxy.yml  | cut -f2 -d ' ')

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/adhawkins-borgbase-${{ steps.get_version.outputs.VERSION }}/*.tar.gz
